server:
  port: 8080
spring:
  application:
    name: projectintegrer
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-system
    username: postgres
    password: 'Abc123*'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day

springdoc:
  api-docs:
    path: /docs/api-docs
    enabled: true
  swagger-ui:
    path: /docs/swagger-ui.html
    operations-sorter: method
    enabled: true
  packages-to-scan: com.projecti.projectintegrer.controller
  paths-to-match: /api/**