spring:

  datasource:
    url: jdbc:h2:mem:TEST
    username: sa
    driver-class-name: org.h2.Driver
    password: Test1234!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
application:
  security:
    jwt:
      secret-key: 9ce791e509b1316df57f632b6f75ed35e3ce5992a3f1e9f58c7b93d85193e2bd
      expiration: 86400000 # a day